---

- name: Check whether the postgres data directory is initialized
  stat:
    path: '{{ postgresql_server__data_directory }}/PG_VERSION'
  register: _postgresql_server__pgdata_dir_initialized

- name: Initialize the database
  become: true
  become_user: '{{ postgresql_server__service_user }}'
  command: >-
    {% if ansible_check_mode %} /usr/bin/env echo 'DATABASE MUST BE INITIALIZED WITH '{% endif %}
    {{ postgresql_server__bin_directory }}/initdb
    --pgdata={{ postgresql_server__data_directory }}
    --locale={{ postgresql_server__locale }}
    --encoding={{ postgresql_server__encoding }}
  when: not _postgresql_server__pgdata_dir_initialized.stat.exists
  check_mode: false
  notify: ['restart-postgresql-server']

- name: Create symlink for postgresql.conf in data directory
  file:
    src: '{{ postgresql_server__conf_directory }}/postgresql.conf'
    dest: '{{ postgresql_server__data_directory }}/postgresql.conf'
    owner: '{{ postgresql_server__service_user }}'
    group: '{{ postgresql_server__service_group }}'
    force: true
    state: link
  notify: ['restart-postgresql-server']
