---
# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).
- name: Make sure the CA certificates are available
  yum:
    name: ca-certificates
    state: present
  tags: ['postgresql-server', 'postgresql-server-install']

- name: Add PostgreSQL repository
  yum:
    name: '{{ postgresql_server__yum_repository_url }}'
    state: present
  tags: ['postgresql-server', 'postgresql-server-install']
