---

- name: Add repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    filename: postgresql
    update_cache: true
    state: present
  tags: ['postgresql-server', 'postgresql-server-install']

- name: Add APT key
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags: ['postgresql-server', 'postgresql-server-install']
