---

- name: Install the required packages
  package:
    name: '{{ postgresql_server__required_packages_names|list }}'
    state: present

- include_tasks: install_apt.yml
  when: ansible_pkg_mgr == 'apt'

- include_tasks: install_yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: Install PostgreSQL
  package:
    name: '{{ postgresql_server__packages_names|list }}'
    state: present

- import_tasks: install_extensions.yml
