---
# tasks file for postgresql

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: This module only works with systemd
  when: not ansible_service_mgr in ['systemd']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['postgresql-server', 'postgresql-server-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['postgresql-server', 'postgresql-server-configure']

- name: Importing service tasks
  import_tasks: service.yml
  tags: ['postgresql-server', 'postgresql-server-service']

- meta: flush_handlers
  tags: ['always']

- name: Optionally including users tasks
  include_tasks: users.yml
  when: postgresql_server__service_enabled|bool
  tags: ['postgresql-server', 'postgresql-server-users']

- name: Optionally including databases tasks
  include_tasks: databases.yml
  when: postgresql_server__service_enabled|bool
  tags: ['postgresql-server', 'postgresql-server-databases']
