---
- name: Assert users settings
  fail:
    msg: 'You cannot set a user settings that is already set in the user profile'
  with_dict: "{{ postgresql__users }}"
  when: item.value.profile is defined and item.value.profile in postgresql__profiles.keys() 
          and (item.value.keys() | intersect(postgresql__profiles[item.value.profile].keys()) ) | length != 0

- name: Check users profile
  assert:
    that:
      - item.value.profile is not defined or item.value.profile is defined and item.value.profile in postgresql__profiles.keys()
  with_dict: "{{ postgresql__users }}"

- name: Apply user profile
  set_fact:
    postgresql__users: '{{ postgresql__users|combine({item.key: (item.value | combine(postgresql__profiles[item.value.profile]))}) }}'
  with_dict: '{{ postgresql__users }}'
  when: item.value.profile is defined and item.value.profile in postgresql__profiles.keys()

- name: Ensure PostgreSQL is running
  service:
    name:  '{{ postgresql__service_name }}'
    state: started

- name: Setup PostgreSQL users
  become:      yes
  become_user: '{{ postgresql__admin_user }}'
  postgresql_user:
    name:            '{{ item.key }}'
    password:        '{{ item.value.password|d(omit) }}'
    encrypted:       '{{ item.value.encrypted|d(true) }}'
    expires:         '{{ item.value.expires|d(omit) }}'
    #conn_limit:    "{{ item.value.connection_limit | default(omit) }}"
    role_attr_flags: "{% if item.value.role_flags is defined %}{{ item.value.role_flags if item.value.role_flags is string else item.value.role_flags|join(',') }}{% else %}{{ omit }}{% endif %}"
    port:            '{{ postgresql__port }}'
    login_user:      '{{ postgresql__admin_user }}'
    state:           present
  with_dict: '{{ postgresql__users }}'
  register: _postgresql__users
  ignore_errors: True
  no_log: yes

- name: Extract error message from users setup
  fail:
    msg: "{{ _postgresql__users.results|reject('success')|map(attribute='msg')|list|join(' ') }}"
  when: _postgresql__users|failed
